### ISSUE TITLE
OESS ARM label change for cloud facilityPort

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/information-model-utils#64]
Currently the oess_scan generate a FacilityPort like the below.

```
    <node id="78">
      <data key="d0">6b1b07bb-9805-482f-9d06-101d9e8e8c0d</data>
      <data key="d1">ConnectionPoint</data>
      <data key="d2">port+al2s:agg3.dall3.net.internet2.edu:TenGigE0/0/0/11/2:Cloud_Facility_AWS:facility_port</data>
      <data key="d3">AWS_US_East__Dallas__agg3.dall3.net.internet2.edu_TenGigE0/0/0/11/2</data>
      <data key="d4">FacilityPort</data>
      <data key="d6">{"bw": 10}</data>
      <data key="d7">{"device_name": "US East (Dallas)", "local_name": "agg3.dall3.net.internet2.edu:TenGigE0/0/0/11/2:peer", "vlan_range": ["1-4095", "1-4095"]}</data>
      <data key="d8">false</data>
      <data key="d13">PDP DALL3-CONN-AWS-3</data>
    </node>
```

* [x] 1. `"d7"` is the labels. We will need to change that into the below.
```
{"device_name": "agg3.dall3.net.internet2.edu", "local_name": "TenGigE0/0/0/11/2", "vlan_range": ["1-4095", "1-4095"], "region": "us-east-2"}
```
* [x] 2. We will also need to translate host connection names like `"US East (Dallas)"` into the normally known `region` names. This has to be through a static mapping that is either configured into the python code or an external config file. (A separate python file could be find.) 
```
CLOUD_REGION_NAME_MAP:
    US East (Virginia): us-east-1
    US East (Ohio): us-east-2
    ...
    US East (Dallas): us-east-2
```

* [x] 3. Also rename the `site` from `Internet2` into `AL2S` in the below line. 
```
        site_name = "Internet2"
```

**Comment by xi-yang** [comment]
For 2, here is an imperfect mapping of the region names. As I2 named the regions by DX locations, the exactly mapped regions are unknown. Educated guess for now and will need to collaborate the info with I2 in the future.

```
REGION_NAME_MAP = {
    "CrossConnect-Dallas-Gov": "eastus2",
    "CrossConnection-Chicago": "westus2",
    "CrossConnection-Dallas": "eastus",
    "CrossConnection-SiliconValley": "westus3",
    "CrossConnection-WashingtonDC": "eastus",
    "CrossConnection-WashingtonDC-Gov": "eastus2",
    "US Central1 (Iowa)": "us-central1",
    "US East (Dallas)": "us-east-3",
    "US East (N. Virginia) - Hosted Connect": "us-east-1",
    "US East (Ohio) Hosted Connect": "us-east-2",
    "US East4 (Northern Virginia)": "us-east-4",
    "US West (N. California) - Hosted Connect": "us-west-1",
    "US West1 (Oregon)": "us-west-2",
    "US West2 (California)": "us-west-3"
}
```

**Comment by xi-yang** [comment]
Pending for I2 to fix the API data. Meanwhile, I see a imperfection in the vlan_range label that has dup ranges ` "vlan_range": ["1-4095", "1-4095"]`. @zlion  can review and fix this part of code.
https://github.com/fabric-testbed/information-model-utils/blob/fc5fa16b60473c5fc1e80942e2b51338e61a213c/fimutil/al2s/oess.py#L207-L213

**Comment by zlion** [comment]
A fix has been checked in and wait for review.
